version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx_testtask2
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grafana

  grafana:
    image: grafana/grafana
    container_name: grafana_testtask2
    restart: always
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus_testtask2
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.route-prefix=/
      - --web.external-url=http://localhost/prometheus
    volumes:
      - ./prometheus:/etc/prometheus

  node_exp:
    image: prom/node-exporter
    container_name: node-exporter_testtask2
    restart: always
