version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx_testtask
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - grafana
      - jbpm

  grafana:
    image: grafana/grafana
    container_name: grafana_testtask
    restart: always
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus_testtask
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.route-prefix=/
      - --web.external-url=http://localhost/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    depends_on:
      - node_exp

  node_exp:
    image: prom/node-exporter
    container_name: node-exporter_testtask
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)

  jbpm:
    image: jboss/jbpm-server-full
    container_name: jbpm_testtask
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: postgres_testtask
      JBPM_DB_PORT: 5432
      JBPM_DB_NAME: jbpm
      JBPM_DB_USER: jbpm
      JBPM_DB_PASSWORD: jbpm
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres_testtask
    restart: always
    environment:
      - POSTGRES_PASSWORD=jbpm
      - POSTGRES_USER=jbpm
      - POSTGRES_DB=jbpm
